import type { City, Route, DestinationTicket } from './gameData.js';

export const INDIA_CITIES: City[] = [
  // Northern India
  { name: 'Srinagar', x: 369, y: 45 },
  { name: 'Leh', x: 575, y: 75 },
  { name: 'Kargil', x: 492, y: 85 },
  { name: 'Amritsar', x: 430, y: 176 },
  { name: 'Shimla', x: 529, y: 200 },
  { name: 'Delhi', x: 482, y: 238 },
  { name: 'Lucknow', x: 660, y: 315 },

  // Rajasthan & Western India
  { name: 'Jaipur', x: 473, y: 345 },
  { name: 'Jodhpur', x: 381, y: 320 },
  { name: 'Jaisalmer', x: 257, y: 307 },
  { name: 'Bhuj', x: 285, y: 385 },
  { name: 'Dwarka', x: 200, y: 393 },
  { name: 'Somnath', x: 265, y: 427 },
  { name: 'Ahmedabad', x: 319, y: 448 },
  { name: 'Surat', x: 213, y: 450 },

  // Central India
  { name: 'Bhopal', x: 591, y: 349 },
  { name: 'Indore', x: 494, y: 428 },
  { name: 'Nagpur', x: 649, y: 443 },

  // Western Coast & Maharashtra
  { name: 'Mumbai', x: 278, y: 487 },
  { name: 'Pune', x: 545, y: 482 },
  { name: 'Goa', x: 319, y: 523 },

  // Eastern India
  { name: 'Patna', x: 817, y: 349 },
  { name: 'Kolkata', x: 826, y: 480 },
  { name: 'Visakhapatnam', x: 699, y: 538 },
  { name: 'Darjeeling', x: 818, y: 286 },

  // Northeast India
  { name: 'Guwahati', x: 961, y: 330 },
  { name: 'Dibrugarh', x: 1042, y: 230 },
  { name: 'Imphal', x: 975, y: 468 },

  // South India
  { name: 'Hyderabad', x: 531, y: 555 },
  { name: 'Chennai', x: 561, y: 653 },
  { name: 'Bangalore', x: 457, y: 638 },
  { name: 'Mangalore', x: 388, y: 544 },
  { name: 'Kochi', x: 359, y: 673 },
  { name: 'Madurai', x: 473, y: 726 },
  { name: 'Kanyakumari', x: 452, y: 847 },
];

export const INDIA_ROUTES: Route[] = [
  // ===== BOUNDARY PATH =====
  { id: 'sri_kar', city1: 'Srinagar', city2: 'Kargil', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'kar_leh', city1: 'Kargil', city2: 'Leh', length: 2, color: 'GREY', claimedBy: null },
  { id: 'leh_shi', city1: 'Leh', city2: 'Shimla', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'shi_luc', city1: 'Shimla', city2: 'Lucknow', length: 5, color: 'RED', claimedBy: null },
  { id: 'luc_pat', city1: 'Lucknow', city2: 'Patna', length: 4, color: 'BLUE', claimedBy: null },
  { id: 'pat_dar', city1: 'Patna', city2: 'Darjeeling', length: 1, color: 'YELLOW', claimedBy: null },
  { id: 'dar_guw', city1: 'Darjeeling', city2: 'Guwahati', length: 4, color: 'GREEN', claimedBy: null },
  { id: 'guw_dib', city1: 'Guwahati', city2: 'Dibrugarh', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'dib_imp', city1: 'Dibrugarh', city2: 'Imphal', length: 6, color: 'PURPLE', claimedBy: null },
  { id: 'imp_kol', city1: 'Imphal', city2: 'Kolkata', length: 4, color: 'GREY', claimedBy: null },
  { id: 'kol_vis', city1: 'Kolkata', city2: 'Visakhapatnam', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'vis_che', city1: 'Visakhapatnam', city2: 'Chennai', length: 5, color: 'WHITE', claimedBy: null },
  { id: 'che_mad', city1: 'Chennai', city2: 'Madurai', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'mad_kan', city1: 'Madurai', city2: 'Kanyakumari', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'kan_koc', city1: 'Kanyakumari', city2: 'Kochi', length: 6, color: 'GREEN', claimedBy: null },
  { id: 'koc_man', city1: 'Kochi', city2: 'Mangalore', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'man_goa', city1: 'Mangalore', city2: 'Goa', length: 2, color: 'PURPLE', claimedBy: null },
  { id: 'goa_mum', city1: 'Goa', city2: 'Mumbai', length: 1, color: 'GREY', claimedBy: null },
  { id: 'mum_sur', city1: 'Mumbai', city2: 'Surat', length: 2, color: 'RED', claimedBy: null },
  { id: 'sur_som', city1: 'Surat', city2: 'Somnath', length: 1, color: 'ORANGE', claimedBy: null },
  { id: 'som_dwa', city1: 'Somnath', city2: 'Dwarka', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'dwa_bhu', city1: 'Dwarka', city2: 'Bhuj', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'bhu_jas', city1: 'Bhuj', city2: 'Jaisalmer', length: 2, color: 'GREEN', claimedBy: null },
  { id: 'jas_jod', city1: 'Jaisalmer', city2: 'Jodhpur', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'jod_amr', city1: 'Jodhpur', city2: 'Amritsar', length: 4, color: 'PURPLE', claimedBy: null },
  { id: 'amr_sri', city1: 'Amritsar', city2: 'Srinagar', length: 4, color: 'BLACK', claimedBy: null },

  // ===== INTERNAL CONNECTORS =====
  { id: 'del_amr1', city1: 'Delhi', city2: 'Amritsar', length: 2, color: 'GREY', claimedBy: null },
  { id: 'del_amr2', city1: 'Delhi', city2: 'Amritsar', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'del_shi', city1: 'Delhi', city2: 'Shimla', length: 1, color: 'YELLOW', claimedBy: null },
  { id: 'del_luc1', city1: 'Delhi', city2: 'Lucknow', length: 6, color: 'GREEN', claimedBy: null },
  { id: 'del_luc2', city1: 'Delhi', city2: 'Lucknow', length: 6, color: 'PURPLE', claimedBy: null },
  { id: 'del_bho', city1: 'Delhi', city2: 'Bhopal', length: 4, color: 'WHITE', claimedBy: null },
  { id: 'del_jai1', city1: 'Delhi', city2: 'Jaipur', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'del_jai2', city1: 'Delhi', city2: 'Jaipur', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'jai_jod', city1: 'Jaipur', city2: 'Jodhpur', length: 2, color: 'RED', claimedBy: null },
  { id: 'jai_jas', city1: 'Jaipur', city2: 'Jaisalmer', length: 6, color: 'ORANGE', claimedBy: null },
  { id: 'jai_bho', city1: 'Jaipur', city2: 'Bhopal', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'jai_ind', city1: 'Jaipur', city2: 'Indore', length: 2, color: 'GREY', claimedBy: null },
  { id: 'jai_ahm', city1: 'Jaipur', city2: 'Ahmedabad', length: 5, color: 'PURPLE', claimedBy: null },
  { id: 'bho_luc', city1: 'Bhopal', city2: 'Lucknow', length: 2, color: 'ORANGE', claimedBy: null },
  { id: 'bho_pat', city1: 'Bhopal', city2: 'Patna', length: 6, color: 'RED', claimedBy: null },
  { id: 'bho_nag1', city1: 'Bhopal', city2: 'Nagpur', length: 3, color: 'GREY', claimedBy: null },
  { id: 'bho_nag2', city1: 'Bhopal', city2: 'Nagpur', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'bho_ind', city1: 'Bhopal', city2: 'Indore', length: 3, color: 'GREEN', claimedBy: null },
  { id: 'ind_ahm', city1: 'Indore', city2: 'Ahmedabad', length: 5, color: 'YELLOW', claimedBy: null },
  { id: 'ind_nag', city1: 'Indore', city2: 'Nagpur', length: 4, color: 'WHITE', claimedBy: null },
  { id: 'ind_pun', city1: 'Indore', city2: 'Pune', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'nag_pat', city1: 'Nagpur', city2: 'Patna', length: 6, color: 'BLACK', claimedBy: null },
  { id: 'nag_kol', city1: 'Nagpur', city2: 'Kolkata', length: 5, color: 'GREEN', claimedBy: null },
  { id: 'nag_vis', city1: 'Nagpur', city2: 'Visakhapatnam', length: 3, color: 'PURPLE', claimedBy: null },
  { id: 'nag_hyd', city1: 'Nagpur', city2: 'Hyderabad', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'nag_pun', city1: 'Nagpur', city2: 'Pune', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'hyd_vis', city1: 'Hyderabad', city2: 'Visakhapatnam', length: 4, color: 'GREY', claimedBy: null },
  { id: 'hyd_che1', city1: 'Hyderabad', city2: 'Chennai', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'hyd_che2', city1: 'Hyderabad', city2: 'Chennai', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'hyd_ban', city1: 'Hyderabad', city2: 'Bangalore', length: 3, color: 'RED', claimedBy: null },
  { id: 'hyd_pun', city1: 'Hyderabad', city2: 'Pune', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'ban_man', city1: 'Bangalore', city2: 'Mangalore', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'ban_che1', city1: 'Bangalore', city2: 'Chennai', length: 3, color: 'PURPLE', claimedBy: null },
  { id: 'ban_che2', city1: 'Bangalore', city2: 'Chennai', length: 3, color: 'RED', claimedBy: null },
  { id: 'ban_mad', city1: 'Bangalore', city2: 'Madurai', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'ban_koc', city1: 'Bangalore', city2: 'Kochi', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'pun_mum1', city1: 'Pune', city2: 'Mumbai', length: 6, color: 'RED', claimedBy: null },
  { id: 'pun_mum2', city1: 'Pune', city2: 'Mumbai', length: 6, color: 'WHITE', claimedBy: null },
  { id: 'pun_goa', city1: 'Pune', city2: 'Goa', length: 6, color: 'BLACK', claimedBy: null },
  { id: 'kol_pat1', city1: 'Kolkata', city2: 'Patna', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'kol_pat2', city1: 'Kolkata', city2: 'Patna', length: 3, color: 'GREY', claimedBy: null },
  { id: 'kol_dar', city1: 'Kolkata', city2: 'Darjeeling', length: 6, color: 'BLUE', claimedBy: null },
  { id: 'kol_guw', city1: 'Kolkata', city2: 'Guwahati', length: 6, color: 'YELLOW', claimedBy: null },
  { id: 'ahm_sur', city1: 'Ahmedabad', city2: 'Surat', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'ahm_bhu', city1: 'Ahmedabad', city2: 'Bhuj', length: 1, color: 'BLACK', claimedBy: null },
  { id: 'ahm_mum1', city1: 'Ahmedabad', city2: 'Mumbai', length: 1, color: 'GREEN', claimedBy: null },
  { id: 'ahm_mum2', city1: 'Ahmedabad', city2: 'Mumbai', length: 1, color: 'GREY', claimedBy: null },
  { id: 'sri_leh', city1: 'Srinagar', city2: 'Leh', length: 6, color: 'GREY', claimedBy: null },
  { id: 'guw_imp', city1: 'Guwahati', city2: 'Imphal', length: 4, color: 'ORANGE', claimedBy: null },

];

export const INDIA_DESTINATION_TICKETS: DestinationTicket[] = [
  // Long-haul routes (14+ points) — Cross-country epics
  { id: 'it1', city1: 'Srinagar', city2: 'Kanyakumari', points: 23 },
  { id: 'it2', city1: 'Amritsar', city2: 'Chennai', points: 14 },
  { id: 'it3', city1: 'Jaisalmer', city2: 'Imphal', points: 20 },
  { id: 'it4', city1: 'Delhi', city2: 'Kanyakumari', points: 17 },
  { id: 'it5', city1: 'Srinagar', city2: 'Kolkata', points: 18 },
  { id: 'it6', city1: 'Mumbai', city2: 'Kolkata', points: 14 },
  { id: 'it7', city1: 'Delhi', city2: 'Kanyakumari', points: 17 },
  { id: 'it8', city1: 'Jaisalmer', city2: 'Kanyakumari', points: 15 },
  { id: 'it9', city1: 'Amritsar', city2: 'Bangalore', points: 14 },
  { id: 'it10', city1: 'Guwahati', city2: 'Mumbai', points: 20 },

  // Medium routes (8-13 points) — Regional journeys
  { id: 'it11', city1: 'Delhi', city2: 'Mumbai', points: 9 },
  { id: 'it12', city1: 'Delhi', city2: 'Kolkata', points: 12 },
  { id: 'it13', city1: 'Mumbai', city2: 'Chennai', points: 9 },
  { id: 'it14', city1: 'Kolkata', city2: 'Chennai', points: 9 },
  { id: 'it15', city1: 'Hyderabad', city2: 'Delhi', points: 9 },
  { id: 'it17', city1: 'Bangalore', city2: 'Kolkata', points: 11 },
  { id: 'it19', city1: 'Patna', city2: 'Bangalore', points: 13 },
  { id: 'it20', city1: 'Nagpur', city2: 'Kochi', points: 10 },

  // Short routes (4-7 points) — Quick connections
  { id: 'it16', city1: 'Jaipur', city2: 'Hyderabad', points: 6 },
  { id: 'it18', city1: 'Mumbai', city2: 'Goa', points: 4 },
  { id: 'it21', city1: 'Delhi', city2: 'Kargil', points: 6 },
  { id: 'it22', city1: 'Mumbai', city2: 'Pune', points: 6 },
  { id: 'it23', city1: 'Bangalore', city2: 'Chennai', points: 4 },
  { id: 'it24', city1: 'Kolkata', city2: 'Darjeeling', points: 4 },
  { id: 'it25', city1: 'Lucknow', city2: 'Patna', points: 4 },
  { id: 'it26', city1: 'Kochi', city2: 'Kanyakumari', points: 6 },
  { id: 'it27', city1: 'Ahmedabad', city2: 'Jaipur', points: 5 },
  { id: 'it28', city1: 'Shimla', city2: 'Lucknow', points: 5 },
  { id: 'it29', city1: 'Guwahati', city2: 'Imphal', points: 4 },
  { id: 'it30', city1: 'Patna', city2: 'Nagpur', points: 6 },
];
