import type { City, Route, DestinationTicket } from './gameData.js';

export const INDIA_CITIES: City[] = [
  // Northern India
  { name: 'Srinagar', x: 190, y: 8 },
  { name: 'Leh', x: 412, y: 46 },
  { name: 'Kargil', x: 322, y: 59 },
  { name: 'Amritsar', x: 255, y: 174 },
  { name: 'Shimla', x: 362, y: 203 },
  { name: 'Delhi', x: 312, y: 251 },
  { name: 'Lucknow', x: 502, y: 347 },

  // Rajasthan & Western India
  { name: 'Jaipur', x: 302, y: 385 },
  { name: 'Jodhpur', x: 203, y: 353 },
  { name: 'Jaisalmer', x: 70, y: 337 },
  { name: 'Bhuj', x: 99, y: 435 },
  { name: 'Dwarka', x: 9, y: 445 },
  { name: 'Somnath', x: 79, y: 487 },
  { name: 'Ahmedabad', x: 136, y: 514 },
  { name: 'Surat', x: 22, y: 517 },

  // Central India
  { name: 'Bhopal', x: 428, y: 390 },
  { name: 'Indore', x: 324, y: 488 },
  { name: 'Nagpur', x: 491, y: 507 },

  // Western Coast & Maharashtra
  { name: 'Mumbai', x: 92, y: 563 },
  { name: 'Pune', x: 380, y: 556 },
  { name: 'Goa', x: 136, y: 608 },

  // Eastern India
  { name: 'Patna', x: 672, y: 390 },
  { name: 'Kolkata', x: 681, y: 554 },
  { name: 'Visakhapatnam', x: 544, y: 627 },
  { name: 'Darjeeling', x: 673, y: 312 },

  // Northeast India
  { name: 'Guwahati', x: 826, y: 367 },
  { name: 'Dibrugarh', x: 913, y: 240 },
  { name: 'Imphal', x: 840, y: 539 },

  // South India
  { name: 'Hyderabad', x: 364, y: 648 },
  { name: 'Chennai', x: 396, y: 770 },
  { name: 'Bangalore', x: 285, y: 752 },
  { name: 'Mangalore', x: 211, y: 634 },
  { name: 'Kochi', x: 179, y: 797 },
  { name: 'Madurai', x: 302, y: 863 },
  { name: 'Kanyakumari', x: 279, y: 1013 },
];

export const INDIA_ROUTES: Route[] = [
  // ===== BOUNDARY PATH =====
  { id: 'sri_kar', city1: 'Srinagar', city2: 'Kargil', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'kar_leh', city1: 'Kargil', city2: 'Leh', length: 2, color: 'GREY', claimedBy: null },
  { id: 'leh_shi', city1: 'Leh', city2: 'Shimla', length: 4, color: 'WHITE', claimedBy: null },
  { id: 'shi_luc', city1: 'Shimla', city2: 'Lucknow', length: 6, color: 'RED', claimedBy: null },
  { id: 'luc_pat', city1: 'Lucknow', city2: 'Patna', length: 5, color: 'BLUE', claimedBy: null },
  { id: 'pat_dar', city1: 'Patna', city2: 'Darjeeling', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'dar_guw', city1: 'Darjeeling', city2: 'Guwahati', length: 4, color: 'GREEN', claimedBy: null },
  { id: 'guw_dib', city1: 'Guwahati', city2: 'Dibrugarh', length: 4, color: 'BLACK', claimedBy: null },
  { id: 'dib_imp', city1: 'Dibrugarh', city2: 'Imphal', length: 6, color: 'PURPLE', claimedBy: null },
  { id: 'imp_kol', city1: 'Imphal', city2: 'Kolkata', length: 4, color: 'GREY', claimedBy: null },
  { id: 'kol_vis', city1: 'Kolkata', city2: 'Visakhapatnam', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'vis_che', city1: 'Visakhapatnam', city2: 'Chennai', length: 6, color: 'WHITE', claimedBy: null },
  { id: 'che_mad', city1: 'Chennai', city2: 'Madurai', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'mad_kan', city1: 'Madurai', city2: 'Kanyakumari', length: 4, color: 'BLACK', claimedBy: null },
  { id: 'kan_koc', city1: 'Kanyakumari', city2: 'Kochi', length: 6, color: 'GREEN', claimedBy: null },
  { id: 'koc_man', city1: 'Kochi', city2: 'Mangalore', length: 4, color: 'BLUE', claimedBy: null },
  { id: 'man_goa', city1: 'Mangalore', city2: 'Goa', length: 2, color: 'PURPLE', claimedBy: null },
  { id: 'goa_mum', city1: 'Goa', city2: 'Mumbai', length: 1, color: 'GREY', claimedBy: null },
  { id: 'mum_sur', city1: 'Mumbai', city2: 'Surat', length: 2, color: 'RED', claimedBy: null },
  { id: 'sur_som', city1: 'Surat', city2: 'Somnath', length: 1, color: 'ORANGE', claimedBy: null },
  { id: 'som_dwa', city1: 'Somnath', city2: 'Dwarka', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'dwa_bhu', city1: 'Dwarka', city2: 'Bhuj', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'bhu_jas', city1: 'Bhuj', city2: 'Jaisalmer', length: 3, color: 'GREEN', claimedBy: null },
  { id: 'jas_jod', city1: 'Jaisalmer', city2: 'Jodhpur', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'jod_amr', city1: 'Jodhpur', city2: 'Amritsar', length: 5, color: 'PURPLE', claimedBy: null },
  { id: 'amr_sri', city1: 'Amritsar', city2: 'Srinagar', length: 5, color: 'BLACK', claimedBy: null },

  // ===== INTERNAL CONNECTORS =====
  { id: 'del_amr1', city1: 'Delhi', city2: 'Amritsar', length: 2, color: 'GREY', claimedBy: null },
  { id: 'del_amr2', city1: 'Delhi', city2: 'Amritsar', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'del_shi', city1: 'Delhi', city2: 'Shimla', length: 1, color: 'YELLOW', claimedBy: null },
  { id: 'del_luc1', city1: 'Delhi', city2: 'Lucknow', length: 6, color: 'GREEN', claimedBy: null },
  { id: 'del_luc2', city1: 'Delhi', city2: 'Lucknow', length: 6, color: 'PURPLE', claimedBy: null },
  { id: 'del_bho', city1: 'Delhi', city2: 'Bhopal', length: 5, color: 'WHITE', claimedBy: null },
  { id: 'del_jai1', city1: 'Delhi', city2: 'Jaipur', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'del_jai2', city1: 'Delhi', city2: 'Jaipur', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'jai_jod', city1: 'Jaipur', city2: 'Jodhpur', length: 3, color: 'RED', claimedBy: null },
  { id: 'jai_jas', city1: 'Jaipur', city2: 'Jaisalmer', length: 6, color: 'ORANGE', claimedBy: null },
  { id: 'jai_bho', city1: 'Jaipur', city2: 'Bhopal', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'jai_ind', city1: 'Jaipur', city2: 'Indore', length: 3, color: 'GREY', claimedBy: null },
  { id: 'jai_ahm', city1: 'Jaipur', city2: 'Ahmedabad', length: 6, color: 'PURPLE', claimedBy: null },
  { id: 'bho_luc', city1: 'Bhopal', city2: 'Lucknow', length: 2, color: 'ORANGE', claimedBy: null },
  { id: 'bho_pat', city1: 'Bhopal', city2: 'Patna', length: 6, color: 'RED', claimedBy: null },
  { id: 'bho_nag1', city1: 'Bhopal', city2: 'Nagpur', length: 3, color: 'GREY', claimedBy: null },
  { id: 'bho_nag2', city1: 'Bhopal', city2: 'Nagpur', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'bho_ind', city1: 'Bhopal', city2: 'Indore', length: 4, color: 'GREEN', claimedBy: null },
  { id: 'ind_ahm', city1: 'Indore', city2: 'Ahmedabad', length: 5, color: 'YELLOW', claimedBy: null },
  { id: 'ind_nag', city1: 'Indore', city2: 'Nagpur', length: 4, color: 'WHITE', claimedBy: null },
  { id: 'ind_pun', city1: 'Indore', city2: 'Pune', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'nag_pat', city1: 'Nagpur', city2: 'Patna', length: 6, color: 'BLACK', claimedBy: null },
  { id: 'nag_kol', city1: 'Nagpur', city2: 'Kolkata', length: 6, color: 'GREEN', claimedBy: null },
  { id: 'nag_vis', city1: 'Nagpur', city2: 'Visakhapatnam', length: 3, color: 'PURPLE', claimedBy: null },
  { id: 'nag_hyd', city1: 'Nagpur', city2: 'Hyderabad', length: 5, color: 'ORANGE', claimedBy: null },
  { id: 'nag_pun', city1: 'Nagpur', city2: 'Pune', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'hyd_vis', city1: 'Hyderabad', city2: 'Visakhapatnam', length: 5, color: 'GREY', claimedBy: null },
  { id: 'hyd_che1', city1: 'Hyderabad', city2: 'Chennai', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'hyd_che2', city1: 'Hyderabad', city2: 'Chennai', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'hyd_ban', city1: 'Hyderabad', city2: 'Bangalore', length: 3, color: 'RED', claimedBy: null },
  { id: 'hyd_pun', city1: 'Hyderabad', city2: 'Pune', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'ban_man', city1: 'Bangalore', city2: 'Mangalore', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'ban_che1', city1: 'Bangalore', city2: 'Chennai', length: 3, color: 'PURPLE', claimedBy: null },
  { id: 'ban_che2', city1: 'Bangalore', city2: 'Chennai', length: 3, color: 'RED', claimedBy: null },
  { id: 'ban_mad', city1: 'Bangalore', city2: 'Madurai', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'ban_koc', city1: 'Bangalore', city2: 'Kochi', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'pun_mum1', city1: 'Pune', city2: 'Mumbai', length: 6, color: 'RED', claimedBy: null },
  { id: 'pun_mum2', city1: 'Pune', city2: 'Mumbai', length: 6, color: 'WHITE', claimedBy: null },
  { id: 'pun_goa', city1: 'Pune', city2: 'Goa', length: 6, color: 'BLACK', claimedBy: null },
  { id: 'kol_pat1', city1: 'Kolkata', city2: 'Patna', length: 4, color: 'WHITE', claimedBy: null },
  { id: 'kol_pat2', city1: 'Kolkata', city2: 'Patna', length: 4, color: 'GREY', claimedBy: null },
  { id: 'kol_dar', city1: 'Kolkata', city2: 'Darjeeling', length: 6, color: 'BLUE', claimedBy: null },
  { id: 'kol_guw', city1: 'Kolkata', city2: 'Guwahati', length: 6, color: 'YELLOW', claimedBy: null },
  { id: 'ahm_sur', city1: 'Ahmedabad', city2: 'Surat', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'ahm_bhu', city1: 'Ahmedabad', city2: 'Bhuj', length: 2, color: 'BLACK', claimedBy: null },
  { id: 'ahm_mum1', city1: 'Ahmedabad', city2: 'Mumbai', length: 1, color: 'GREEN', claimedBy: null },
  { id: 'ahm_mum2', city1: 'Ahmedabad', city2: 'Mumbai', length: 1, color: 'GREY', claimedBy: null },
  { id: 'sri_leh', city1: 'Srinagar', city2: 'Leh', length: 6, color: 'GREY', claimedBy: null },
  { id: 'guw_imp', city1: 'Guwahati', city2: 'Imphal', length: 5, color: 'ORANGE', claimedBy: null },

];

export const INDIA_DESTINATION_TICKETS: DestinationTicket[] = [
  // Long-haul routes (14+ points) — Cross-country epics
  { id: 'it1', city1: 'Srinagar', city2: 'Kanyakumari', points: 27 },
  { id: 'it2', city1: 'Amritsar', city2: 'Chennai', points: 15 },
  { id: 'it3', city1: 'Jaisalmer', city2: 'Imphal', points: 22 },
  { id: 'it4', city1: 'Delhi', city2: 'Kanyakumari', points: 20 },
  { id: 'it5', city1: 'Srinagar', city2: 'Kolkata', points: 21 },
  { id: 'it6', city1: 'Mumbai', city2: 'Kolkata', points: 15 },
  { id: 'it7', city1: 'Delhi', city2: 'Kanyakumari', points: 20 },
  { id: 'it8', city1: 'Jaisalmer', city2: 'Kanyakumari', points: 19 },
  { id: 'it9', city1: 'Amritsar', city2: 'Bangalore', points: 15 },
  { id: 'it10', city1: 'Guwahati', city2: 'Mumbai', points: 21 },
  { id: 'it12', city1: 'Delhi', city2: 'Kolkata', points: 14 },
  { id: 'it19', city1: 'Patna', city2: 'Bangalore', points: 14 },

  // Medium routes (8-13 points) — Regional journeys
  { id: 'it11', city1: 'Delhi', city2: 'Mumbai', points: 10 },
  { id: 'it13', city1: 'Mumbai', city2: 'Chennai', points: 10 },
  { id: 'it14', city1: 'Kolkata', city2: 'Chennai', points: 10 },
  { id: 'it15', city1: 'Hyderabad', city2: 'Delhi', points: 10 },
  { id: 'it17', city1: 'Bangalore', city2: 'Kolkata', points: 12 },
  { id: 'it20', city1: 'Nagpur', city2: 'Kochi', points: 11 },

  // Short routes (4-7 points) — Quick connections
  { id: 'it16', city1: 'Jaipur', city2: 'Hyderabad', points: 7 },
  { id: 'it18', city1: 'Mumbai', city2: 'Goa', points: 4 },
  { id: 'it21', city1: 'Delhi', city2: 'Kargil', points: 7 },
  { id: 'it22', city1: 'Mumbai', city2: 'Pune', points: 6 },
  { id: 'it23', city1: 'Bangalore', city2: 'Chennai', points: 4 },
  { id: 'it24', city1: 'Kolkata', city2: 'Darjeeling', points: 6 },
  { id: 'it25', city1: 'Lucknow', city2: 'Patna', points: 5 },
  { id: 'it26', city1: 'Kochi', city2: 'Kanyakumari', points: 6 },
  { id: 'it27', city1: 'Ahmedabad', city2: 'Jaipur', points: 6 },
  { id: 'it28', city1: 'Shimla', city2: 'Lucknow', points: 6 },
  { id: 'it29', city1: 'Guwahati', city2: 'Imphal', points: 5 },
  { id: 'it30', city1: 'Patna', city2: 'Nagpur', points: 6 },
];
