import type { City, Route, DestinationTicket } from './gameData.js';

export const INDIA_CITIES: City[] = [
  // Northern India
  { name: 'Srinagar', x: 190, y: 8 },
  { name: 'Leh', x: 412, y: 46 },
  { name: 'Kargil', x: 322, y: 59 },
  { name: 'Amritsar', x: 255, y: 174 },
  { name: 'Shimla', x: 362, y: 203 },
  { name: 'Delhi', x: 312, y: 251 },
  { name: 'Patna', x: 502, y: 347 },

  // Rajasthan & Western India
  { name: 'Gwalior', x: 302, y: 385 },
  { name: 'Jodhpur', x: 203, y: 353 },
  { name: 'Jaisalmer', x: 70, y: 337 },
  { name: 'Bhuj', x: 99, y: 435 },
  { name: 'Dwarka', x: 9, y: 445 },
  { name: 'Ahmedabad', x: 136, y: 514 },
  { name: 'Surat', x: 22, y: 517 },

  // Central India
  { name: 'Lucknow', x: 428, y: 390 },
  { name: 'Indore', x: 324, y: 488 },
  { name: 'Raipur', x: 491, y: 507 },
  { name: 'Nagpur', x: 380, y: 556 },

  // Western Coast & Maharashtra
  { name: 'Khambhat', x: 92, y: 563 },
  { name: 'Mumbai', x: 136, y: 608 },

  // Eastern India
  { name: 'Siliguri', x: 672, y: 390 },
  { name: 'Kolkata', x: 681, y: 554 },
  { name: 'Puri', x: 544, y: 627 },
  { name: 'Gangtok', x: 673, y: 312 },

  // Northeast India
  { name: 'Guwahati', x: 826, y: 367 },
  { name: 'Dibrugarh', x: 913, y: 240 },
  { name: 'Imphal', x: 840, y: 539 },

  // South India
  { name: 'Hyderabad', x: 364, y: 648 },
  { name: 'Chennai', x: 396, y: 770 },
  { name: 'Bangalore', x: 285, y: 752 },
  { name: 'Pune', x: 211, y: 634 },
  { name: 'Goa', x: 179, y: 797 },
  { name: 'Madurai', x: 302, y: 863 },
  { name: 'Kanyakumari', x: 279, y: 1013 },
];

export const INDIA_ROUTES: Route[] = [
  // ===== BOUNDARY PATH =====
  { id: 'sri_kar', city1: 'Srinagar', city2: 'Kargil', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'kar_leh', city1: 'Kargil', city2: 'Leh', length: 2, color: 'GREY', claimedBy: null },
  { id: 'leh_shi', city1: 'Leh', city2: 'Shimla', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'shi_pat', city1: 'Shimla', city2: 'Patna', length: 4, color: 'RED', claimedBy: null },
  { id: 'pat_sil', city1: 'Patna', city2: 'Siliguri', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'sil_gan1', city1: 'Siliguri', city2: 'Gangtok', length: 1, color: 'YELLOW', claimedBy: null },
  { id: 'sil_gan2', city1: 'Siliguri', city2: 'Gangtok', length: 1, color: 'GREY', claimedBy: null },
  { id: 'sil_dib', city1: 'Siliguri', city2: 'Dibrugarh', length: 6, color: 'GREY', claimedBy: null },
  { id: 'dib_imp', city1: 'Dibrugarh', city2: 'Imphal', length: 6, color: 'PURPLE', claimedBy: null },
  { id: 'imp_sil', city1: 'Imphal', city2: 'Siliguri', length: 5, color: 'GREY', claimedBy: null },
  { id: 'sil_kol', city1: 'Siliguri', city2: 'Kolkata', length: 3, color: 'GREY', claimedBy: null },
  { id: 'kol_pur', city1: 'Kolkata', city2: 'Puri', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'pur_che', city1: 'Puri', city2: 'Chennai', length: 4, color: 'WHITE', claimedBy: null },
  { id: 'che_kan', city1: 'Chennai', city2: 'Kanyakumari', length: 6, color: 'BLACK', claimedBy: null },
  { id: 'kan_goa', city1: 'Kanyakumari', city2: 'Goa', length: 5, color: 'GREEN', claimedBy: null },
  { id: 'goa_mum', city1: 'Goa', city2: 'Mumbai', length: 4, color: 'PURPLE', claimedBy: null },
  { id: 'mum_kha', city1: 'Mumbai', city2: 'Khambhat', length: 1, color: 'GREY', claimedBy: null },
  { id: 'kha_sur', city1: 'Khambhat', city2: 'Surat', length: 1, color: 'ORANGE', claimedBy: null },
  { id: 'sur_ahm', city1: 'Surat', city2: 'Ahmedabad', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'ahm_dwa', city1: 'Ahmedabad', city2: 'Dwarka', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'dwa_bhu', city1: 'Dwarka', city2: 'Bhuj', length: 2, color: 'GREEN', claimedBy: null },
  { id: 'bhu_jas', city1: 'Bhuj', city2: 'Jaisalmer', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'jas_amr', city1: 'Jaisalmer', city2: 'Amritsar', length: 5, color: 'PURPLE', claimedBy: null },
  { id: 'amr_sri', city1: 'Amritsar', city2: 'Srinagar', length: 3, color: 'BLACK', claimedBy: null },

  // ===== INTERNAL CONNECTORS =====
  { id: 'del_amr1', city1: 'Delhi', city2: 'Amritsar', length: 2, color: 'GREY', claimedBy: null },
  { id: 'del_amr2', city1: 'Delhi', city2: 'Amritsar', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'del_shi1', city1: 'Delhi', city2: 'Shimla', length: 1, color: 'YELLOW', claimedBy: null },
  { id: 'del_shi2', city1: 'Delhi', city2: 'Shimla', length: 1, color: 'GREY', claimedBy: null },
  { id: 'del_luc', city1: 'Delhi', city2: 'Lucknow', length: 4, color: 'GREEN', claimedBy: null },
  { id: 'del_gwa1', city1: 'Delhi', city2: 'Gwalior', length: 2, color: 'BLACK', claimedBy: null },
  { id: 'del_gwa2', city1: 'Delhi', city2: 'Gwalior', length: 2, color: 'ORANGE', claimedBy: null },
  { id: 'gwa_jod', city1: 'Gwalior', city2: 'Jodhpur', length: 2, color: 'RED', claimedBy: null },
  { id: 'gwa_luc', city1: 'Gwalior', city2: 'Lucknow', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'gwa_ind1', city1: 'Gwalior', city2: 'Indore', length: 2, color: 'GREY', claimedBy: null },
  { id: 'gwa_ind2', city1: 'Gwalior', city2: 'Indore', length: 2, color: 'ORANGE', claimedBy: null },
  { id: 'jod_jas', city1: 'Jodhpur', city2: 'Jaisalmer', length: 2, color: 'GREEN', claimedBy: null },
  { id: 'jod_amr', city1: 'Jodhpur', city2: 'Amritsar', length: 4, color: 'PURPLE', claimedBy: null },
  { id: 'jod_ahm', city1: 'Jodhpur', city2: 'Ahmedabad', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'kar_amr', city1: 'Kargil', city2: 'Amritsar', length: 2, color: 'GREY', claimedBy: null },
  { id: 'kar_shi', city1: 'Kargil', city2: 'Shimla', length: 3, color: 'GREY', claimedBy: null },
  { id: 'luc_pat', city1: 'Lucknow', city2: 'Patna', length: 1, color: 'ORANGE', claimedBy: null },
  { id: 'luc_sil', city1: 'Lucknow', city2: 'Siliguri', length: 5, color: 'RED', claimedBy: null },
  { id: 'luc_raip1', city1: 'Lucknow', city2: 'Raipur', length: 2, color: 'GREY', claimedBy: null },
  { id: 'luc_raip2', city1: 'Lucknow', city2: 'Raipur', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'luc_ind', city1: 'Lucknow', city2: 'Indore', length: 3, color: 'GREEN', claimedBy: null },
  { id: 'ind_ahm', city1: 'Indore', city2: 'Ahmedabad', length: 4, color: 'YELLOW', claimedBy: null },
  { id: 'ind_raip', city1: 'Indore', city2: 'Raipur', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'ind_nag1', city1: 'Indore', city2: 'Nagpur', length: 1, color: 'BLUE', claimedBy: null },
  { id: 'ind_nag2', city1: 'Indore', city2: 'Nagpur', length: 1, color: 'GREY', claimedBy: null },
  { id: 'raip_sil', city1: 'Raipur', city2: 'Siliguri', length: 4, color: 'BLACK', claimedBy: null },
  { id: 'raip_kol', city1: 'Raipur', city2: 'Kolkata', length: 4, color: 'GREEN', claimedBy: null },
  { id: 'raip_pur', city1: 'Raipur', city2: 'Puri', length: 2, color: 'PURPLE', claimedBy: null },
  { id: 'raip_hyd', city1: 'Raipur', city2: 'Hyderabad', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'raip_nag', city1: 'Raipur', city2: 'Nagpur', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'hyd_pur', city1: 'Hyderabad', city2: 'Puri', length: 4, color: 'GREY', claimedBy: null },
  { id: 'hyd_che1', city1: 'Hyderabad', city2: 'Chennai', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'hyd_che2', city1: 'Hyderabad', city2: 'Chennai', length: 2, color: 'ORANGE', claimedBy: null },
  { id: 'hyd_ban', city1: 'Hyderabad', city2: 'Bangalore', length: 2, color: 'RED', claimedBy: null },
  { id: 'nag_hyd1', city1: 'Nagpur', city2: 'Hyderabad', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'nag_hyd2', city1: 'Nagpur', city2: 'Hyderabad', length: 2, color: 'GREY', claimedBy: null },
  { id: 'pun_mum1', city1: 'Pune', city2: 'Mumbai', length: 1, color: 'RED', claimedBy: null },
  { id: 'pun_mum2', city1: 'Pune', city2: 'Mumbai', length: 1, color: 'WHITE', claimedBy: null },
  { id: 'pun_goa', city1: 'Pune', city2: 'Goa', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'pun_hyd', city1: 'Pune', city2: 'Hyderabad', length: 3, color: 'GREEN', claimedBy: null },
  { id: 'pun_nag', city1: 'Pune', city2: 'Nagpur', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'mum_ind', city1: 'Mumbai', city2: 'Indore', length: 5, color: 'GREY', claimedBy: null },
  { id: 'pun_ind', city1: 'Pune', city2: 'Indore', length: 4, color: 'GREY', claimedBy: null },
  { id: 'ban_goa1', city1: 'Bangalore', city2: 'Goa', length: 2, color: 'ORANGE', claimedBy: null },
  { id: 'ban_goa2', city1: 'Bangalore', city2: 'Goa', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ban_che', city1: 'Bangalore', city2: 'Chennai', length: 2, color: 'PURPLE', claimedBy: null },
  { id: 'ban_mad', city1: 'Bangalore', city2: 'Madurai', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'ban_pun', city1: 'Bangalore', city2: 'Pune', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'mad_kan', city1: 'Madurai', city2: 'Kanyakumari', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'goa_mad', city1: 'Goa', city2: 'Madurai', length: 3, color: 'GREEN', claimedBy: null },
  { id: 'che_mad', city1: 'Chennai', city2: 'Madurai', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'kol_sil1', city1: 'Kolkata', city2: 'Siliguri', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'kol_sil2', city1: 'Kolkata', city2: 'Siliguri', length: 3, color: 'GREY', claimedBy: null },
  { id: 'ahm_sur', city1: 'Ahmedabad', city2: 'Surat', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'ahm_bhu', city1: 'Ahmedabad', city2: 'Bhuj', length: 1, color: 'BLACK', claimedBy: null },
  { id: 'ahm_mum', city1: 'Ahmedabad', city2: 'Mumbai', length: 2, color: 'RED', claimedBy: null },
  { id: 'guw_sil', city1: 'Guwahati', city2: 'Siliguri', length: 3, color: 'GREY', claimedBy: null },
  { id: 'guw_dib', city1: 'Guwahati', city2: 'Dibrugarh', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'guw_imp', city1: 'Guwahati', city2: 'Imphal', length: 3, color: 'ORANGE', claimedBy: null },
];

export const INDIA_DESTINATION_TICKETS: DestinationTicket[] = [
  // Long-haul routes (14+ points) — Cross-country epics
  { id: 'it1', city1: 'Srinagar', city2: 'Kanyakumari', points: 19 },
  { id: 'it3', city1: 'Jaisalmer', city2: 'Imphal', points: 15 },
  { id: 'it4', city1: 'Delhi', city2: 'Kanyakumari', points: 14 },
  { id: 'it5', city1: 'Srinagar', city2: 'Kolkata', points: 15 },
  { id: 'it7', city1: 'Delhi', city2: 'Kanyakumari', points: 14 },
  { id: 'it8', city1: 'Jaisalmer', city2: 'Kanyakumari', points: 14 },
  { id: 'it10', city1: 'Guwahati', city2: 'Khambhat', points: 15 },

  // Medium routes (8-13 points) — Regional journeys
  { id: 'it2', city1: 'Amritsar', city2: 'Chennai', points: 11 },
  { id: 'it6', city1: 'Khambhat', city2: 'Kolkata', points: 12 },
  { id: 'it9', city1: 'Amritsar', city2: 'Bangalore', points: 11 },
  { id: 'it11', city1: 'Delhi', city2: 'Khambhat', points: 10 },
  { id: 'it12', city1: 'Delhi', city2: 'Kolkata', points: 10 },
  { id: 'it17', city1: 'Bangalore', city2: 'Kolkata', points: 9 },
  { id: 'it19', city1: 'Siliguri', city2: 'Bangalore', points: 10 },

  // Short routes (4-7 points) — Quick connections
  { id: 'it13', city1: 'Khambhat', city2: 'Chennai', points: 7 },
  { id: 'it14', city1: 'Kolkata', city2: 'Chennai', points: 7 },
  { id: 'it15', city1: 'Hyderabad', city2: 'Delhi', points: 7 },
  { id: 'it16', city1: 'Gwalior', city2: 'Hyderabad', points: 5 },
  { id: 'it18', city1: 'Khambhat', city2: 'Mumbai', points: 4 },
  { id: 'it20', city1: 'Nagpur', city2: 'Goa', points: 6 },
  { id: 'it21', city1: 'Delhi', city2: 'Kargil', points: 4 },
  { id: 'it22', city1: 'Khambhat', city2: 'Pune', points: 4 },
  { id: 'it23', city1: 'Bangalore', city2: 'Chennai', points: 4 },
  { id: 'it24', city1: 'Kolkata', city2: 'Gangtok', points: 4 },
  { id: 'it25', city1: 'Lucknow', city2: 'Siliguri', points: 4 },
  { id: 'it26', city1: 'Goa', city2: 'Kanyakumari', points: 5 },
  { id: 'it27', city1: 'Ahmedabad', city2: 'Gwalior', points: 5 },
  { id: 'it28', city1: 'Shimla', city2: 'Lucknow', points: 5 },
  { id: 'it29', city1: 'Guwahati', city2: 'Imphal', points: 4 },
  { id: 'it30', city1: 'Siliguri', city2: 'Raipur', points: 4 },
];
