import { City, Route, DestinationTicket } from './gameData.js';

export const EUROPE_CITIES: City[] = [
  { name: 'Lisbon', x: 100, y: 780 },
  { name: 'Madrid', x: 200, y: 740 },
  { name: 'Barcelona', x: 320, y: 690 },
  { name: 'Marseille', x: 450, y: 600 },
  { name: 'Paris', x: 420, y: 440 },
  { name: 'London', x: 350, y: 290 },
  { name: 'Edinburgh', x: 320, y: 140 },
  { name: 'Dublin', x: 220, y: 240 },
  { name: 'Brest', x: 280, y: 430 },
  { name: 'Brussels', x: 470, y: 370 },
  { name: 'Amsterdam', x: 510, y: 310 },
  { name: 'Hamburg', x: 610, y: 260 },
  { name: 'Copenhagen', x: 630, y: 150 },
  { name: 'Oslo', x: 590, y: 50 },
  { name: 'Stockholm', x: 710, y: 50 },
  { name: 'Berlin', x: 690, y: 300 },
  { name: 'Frankfurt', x: 570, y: 420 },
  { name: 'Munich', x: 630, y: 480 },
  { name: 'Zurich', x: 540, y: 520 },
  { name: 'Milan', x: 580, y: 590 },
  { name: 'Venice', x: 650, y: 590 },
  { name: 'Rome', x: 660, y: 720 },
  { name: 'Palermo', x: 690, y: 820 },
  { name: 'Athens', x: 880, y: 800 },
  { name: 'Vienna', x: 750, y: 480 },
  { name: 'Warsaw', x: 830, y: 300 },
  { name: 'Danzig', x: 790, y: 220 },
  { name: 'Riga', x: 890, y: 170 },
  { name: 'St. Petersburg', x: 1050, y: 70 },
  { name: 'Moscow', x: 1140, y: 170 },
  { name: 'Kyiv', x: 1010, y: 380 },
  { name: 'Budapest', x: 820, y: 510 },
  { name: 'Bucharest', x: 940, y: 560 },
  { name: 'Sofia', x: 890, y: 650 },
  { name: 'Constantinople', x: 1040, y: 690 }
];

export const EUROPE_ROUTES: Route[] = [
  // West Europe / Iberia
  { id: 'lis_mad', city1: 'Lisbon', city2: 'Madrid', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'mad_bar', city1: 'Madrid', city2: 'Barcelona', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'mad_mar', city1: 'Madrid', city2: 'Marseille', length: 4, color: 'BLACK', claimedBy: null },
  { id: 'bar_mar', city1: 'Barcelona', city2: 'Marseille', length: 3, color: 'GREY', claimedBy: null },
  { id: 'mar_par', city1: 'Marseille', city2: 'Paris', length: 4, color: 'BLUE', claimedBy: null },
  { id: 'mar_mil', city1: 'Marseille', city2: 'Milan', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'par_bre', city1: 'Paris', city2: 'Brest', length: 2, color: 'GREY', claimedBy: null },
  { id: 'par_bru1', city1: 'Paris', city2: 'Brussels', length: 2, color: 'GREEN', claimedBy: null },
  { id: 'par_bru2', city1: 'Paris', city2: 'Brussels', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'par_fra1', city1: 'Paris', city2: 'Frankfurt', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'par_fra2', city1: 'Paris', city2: 'Frankfurt', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'par_zur', city1: 'Paris', city2: 'Zurich', length: 3, color: 'GREY', claimedBy: null },
  { id: 'bre_lon', city1: 'Brest', city2: 'London', length: 2, color: 'BLUE', claimedBy: null },

  // British Isles & North Sea
  { id: 'lon_dub', city1: 'London', city2: 'Dublin', length: 2, color: 'GREY', claimedBy: null },
  { id: 'dub_edi', city1: 'Dublin', city2: 'Edinburgh', length: 2, color: 'BLACK', claimedBy: null },
  { id: 'lon_edi', city1: 'London', city2: 'Edinburgh', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'lon_par1', city1: 'London', city2: 'Paris', length: 2, color: 'GREY', claimedBy: null },
  { id: 'lon_par2', city1: 'London', city2: 'Paris', length: 2, color: 'GREY', claimedBy: null },
  { id: 'lon_ams', city1: 'London', city2: 'Amsterdam', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'bru_ams', city1: 'Brussels', city2: 'Amsterdam', length: 1, color: 'GREY', claimedBy: null },
  { id: 'bru_fra', city1: 'Brussels', city2: 'Frankfurt', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'ams_ham', city1: 'Amsterdam', city2: 'Hamburg', length: 3, color: 'YELLOW', claimedBy: null },

  // Central Europe
  { id: 'fra_ham', city1: 'Frankfurt', city2: 'Hamburg', length: 3, color: 'PURPLE', claimedBy: null },
  { id: 'fra_ber', city1: 'Frankfurt', city2: 'Berlin', length: 3, color: 'RED', claimedBy: null },
  { id: 'fra_mun', city1: 'Frankfurt', city2: 'Munich', length: 2, color: 'GREY', claimedBy: null },
  { id: 'fra_zur', city1: 'Frankfurt', city2: 'Zurich', length: 2, color: 'GREY', claimedBy: null },
  { id: 'mun_zur', city1: 'Munich', city2: 'Zurich', length: 1, color: 'YELLOW', claimedBy: null },
  { id: 'mun_ven', city1: 'Munich', city2: 'Venice', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'mun_vie', city1: 'Munich', city2: 'Vienna', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'mun_ber', city1: 'Munich', city2: 'Berlin', length: 3, color: 'BLACK', claimedBy: null },

  // Scandinavia
  { id: 'ham_cop', city1: 'Hamburg', city2: 'Copenhagen', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ham_ber', city1: 'Hamburg', city2: 'Berlin', length: 2, color: 'RED', claimedBy: null },
  { id: 'cop_osl', city1: 'Copenhagen', city2: 'Oslo', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'cop_sto', city1: 'Copenhagen', city2: 'Stockholm', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'osl_sto', city1: 'Oslo', city2: 'Stockholm', length: 2, color: 'GREY', claimedBy: null },
  { id: 'sto_stp', city1: 'Stockholm', city2: 'St. Petersburg', length: 4, color: 'WHITE', claimedBy: null },

  // East Europe / Baltics
  { id: 'ber_dan', city1: 'Berlin', city2: 'Danzig', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ber_war1', city1: 'Berlin', city2: 'Warsaw', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'ber_war2', city1: 'Berlin', city2: 'Warsaw', length: 3, color: 'GREY', claimedBy: null },
  { id: 'ber_vie', city1: 'Berlin', city2: 'Vienna', length: 3, color: 'GREEN', claimedBy: null },
  { id: 'dan_war', city1: 'Danzig', city2: 'Warsaw', length: 2, color: 'RED', claimedBy: null },
  { id: 'dan_rig', city1: 'Danzig', city2: 'Riga', length: 3, color: 'GREY', claimedBy: null },
  { id: 'rig_stp', city1: 'Riga', city2: 'St. Petersburg', length: 4, color: 'RED', claimedBy: null },
  { id: 'rig_war', city1: 'Riga', city2: 'Warsaw', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'stp_mos', city1: 'St. Petersburg', city2: 'Moscow', length: 4, color: 'BLACK', claimedBy: null },
  { id: 'stp_kyi', city1: 'St. Petersburg', city2: 'Kyiv', length: 5, color: 'GREY', claimedBy: null },
  { id: 'mos_kyi', city1: 'Moscow', city2: 'Kyiv', length: 4, color: 'BLUE', claimedBy: null },
  { id: 'war_kyi', city1: 'Warsaw', city2: 'Kyiv', length: 3, color: 'GREY', claimedBy: null },

  // Southeast Europe & Balkans
  { id: 'war_bud', city1: 'Warsaw', city2: 'Budapest', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'vie_bud1', city1: 'Vienna', city2: 'Budapest', length: 2, color: 'RED', claimedBy: null },
  { id: 'vie_bud2', city1: 'Vienna', city2: 'Budapest', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'vie_war', city1: 'Vienna', city2: 'Warsaw', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'ven_mil', city1: 'Venice', city2: 'Milan', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'ven_rom', city1: 'Venice', city2: 'Rome', length: 2, color: 'PURPLE', claimedBy: null },
  { id: 'mil_zur', city1: 'Milan', city2: 'Zurich', length: 2, color: 'GREY', claimedBy: null },
  { id: 'mil_rom', city1: 'Milan', city2: 'Rome', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'rom_pal', city1: 'Rome', city2: 'Palermo', length: 2, color: 'GREY', claimedBy: null },
  { id: 'pal_ath', city1: 'Palermo', city2: 'Athens', length: 4, color: 'GREY', claimedBy: null },
  { id: 'rom_ath', city1: 'Rome', city2: 'Athens', length: 5, color: 'BLUE', claimedBy: null },
  { id: 'ven_bud', city1: 'Venice', city2: 'Budapest', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'bud_kyi', city1: 'Budapest', city2: 'Kyiv', length: 3, color: 'GREY', claimedBy: null },
  { id: 'bud_buc', city1: 'Budapest', city2: 'Bucharest', length: 3, color: 'PURPLE', claimedBy: null },
  { id: 'bud_sof', city1: 'Budapest', city2: 'Sofia', length: 3, color: 'GREEN', claimedBy: null },
  { id: 'sof_buc', city1: 'Sofia', city2: 'Bucharest', length: 2, color: 'GREY', claimedBy: null },
  { id: 'sof_ath', city1: 'Sofia', city2: 'Athens', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'sof_con', city1: 'Sofia', city2: 'Constantinople', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'buc_kyi', city1: 'Bucharest', city2: 'Kyiv', length: 3, color: 'WHITE', claimedBy: null },
  { id: 'buc_con', city1: 'Bucharest', city2: 'Constantinople', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'kyi_con', city1: 'Kyiv', city2: 'Constantinople', length: 4, color: 'GREY', claimedBy: null }
];

export const EUROPE_DESTINATION_TICKETS: DestinationTicket[] = [
  { id: 'et1', city1: 'London', city2: 'Constantinople', points: 20 },
  { id: 'et2', city1: 'Edinburgh', city2: 'Athens', points: 21 },
  { id: 'et3', city1: 'Brest', city2: 'St. Petersburg', points: 20 },
  { id: 'et4', city1: 'Lisbon', city2: 'Moscow', points: 22 },
  { id: 'et5', city1: 'Madrid', city2: 'Berlin', points: 12 },
  { id: 'et6', city1: 'Dublin', city2: 'Paris', points: 7 },
  { id: 'et7', city1: 'London', city2: 'Berlin', points: 8 },
  { id: 'et8', city1: 'Paris', city2: 'Rome', points: 9 },
  { id: 'et9', city1: 'Amsterdam', city2: 'Venice', points: 6 },
  { id: 'et10', city1: 'Hamburg', city2: 'Munich', points: 5 },
  { id: 'et11', city1: 'Copenhagen', city2: 'Oslo', points: 4 },
  { id: 'et12', city1: 'Stockholm', city2: 'Riga', points: 5 },
  { id: 'et13', city1: 'Berlin', city2: 'Moscow', points: 12 },
  { id: 'et14', city1: 'Warsaw', city2: 'Kyiv', points: 6 },
  { id: 'et15', city1: 'Frankfurt', city2: 'Budapest', points: 8 },
  { id: 'et16', city1: 'Munich', city2: 'Constantinople', points: 13 },
  { id: 'et17', city1: 'Vienna', city2: 'Sofia', points: 8 },
  { id: 'et18', city1: 'Rome', city2: 'Athens', points: 8 },
  { id: 'et19', city1: 'Palermo', city2: 'Constantinople', points: 11 },
  { id: 'et20', city1: 'Brest', city2: 'Marseille', points: 6 },
  { id: 'et21', city1: 'Brussels', city2: 'Stockholm', points: 12 },
  { id: 'et22', city1: 'Paris', city2: 'Warsaw', points: 11 },
  { id: 'et23', city1: 'Barcelona', city2: 'Munich', points: 10 },
  { id: 'et24', city1: 'Marseille', city2: 'Vienna', points: 8 },
  { id: 'et25', city1: 'Venice', city2: 'Kyiv', points: 11 },
  { id: 'et26', city1: 'Danzig', city2: 'Bucharest', points: 9 },
  { id: 'et27', city1: 'Kyiv', city2: 'Athens', points: 10 },
  { id: 'et28', city1: 'Bucharest', city2: 'Constantinople', points: 5 },
  { id: 'et29', city1: 'Madrid', city2: 'Rome', points: 10 },
  { id: 'et30', city1: 'Amsterdam', city2: 'Hamburg', points: 4 }
];
