import type { City, Route, DestinationTicket } from './gameData.js';

export const USA_CITIES: City[] = [
  { name: 'Vancouver', x: 100, y: 80 },
  { name: 'Seattle', x: 90, y: 160 },
  { name: 'Portland', x: 80, y: 230 },
  { name: 'San Francisco', x: 60, y: 420 },
  { name: 'Los Angeles', x: 120, y: 580 },
  { name: 'Las Vegas', x: 170, y: 480 },
  { name: 'Calgary', x: 240, y: 60 },
  { name: 'Helena', x: 320, y: 200 },
  { name: 'Salt Lake City', x: 240, y: 370 },
  { name: 'Denver', x: 380, y: 440 },
  { name: 'Santa Fe', x: 360, y: 560 },
  { name: 'El Paso', x: 360, y: 690 },
  { name: 'Phoenix', x: 220, y: 580 },
  { name: 'Winnipeg', x: 490, y: 80 },
  { name: 'Duluth', x: 580, y: 200 },
  { name: 'Omaha', x: 560, y: 370 },
  { name: 'Kansas City', x: 570, y: 450 },
  { name: 'Oklahoma City', x: 560, y: 560 },
  { name: 'Dallas', x: 560, y: 690 },
  { name: 'Houston', x: 590, y: 780 },
  { name: 'Sault Ste Marie', x: 760, y: 180 },
  { name: 'Chicago', x: 760, y: 340 },
  { name: 'Saint Louis', x: 690, y: 420 },
  { name: 'Little Rock', x: 670, y: 560 },
  { name: 'New Orleans', x: 700, y: 760 },
  { name: 'Toronto', x: 920, y: 220 },
  { name: 'Pittsburgh', x: 920, y: 340 },
  { name: 'Nashville', x: 820, y: 450 },
  { name: 'Atlanta', x: 840, y: 540 },
  { name: 'Miami', x: 1000, y: 830 },
  { name: 'Montreal', x: 1050, y: 100 },
  { name: 'Boston', x: 1140, y: 180 },
  { name: 'New York', x: 1080, y: 260 },
  { name: 'Washington', x: 1040, y: 370 },
  { name: 'Richmond', x: 1020, y: 440 },
  { name: 'Raleigh', x: 960, y: 490 },
  { name: 'Charleston', x: 980, y: 580 },
  { name: 'Jacksonville', x: 940, y: 680 }
];

export const USA_ROUTES: Route[] = [
  // West Coast / Northwest
  { id: 'v_c', city1: 'Vancouver', city2: 'Calgary', length: 3, color: 'GREY', claimedBy: null },
  { id: 'v_s1', city1: 'Vancouver', city2: 'Seattle', length: 1, color: 'GREY', claimedBy: null },
  { id: 'v_s2', city1: 'Vancouver', city2: 'Seattle', length: 1, color: 'GREY', claimedBy: null },
  { id: 's_c', city1: 'Seattle', city2: 'Calgary', length: 4, color: 'GREY', claimedBy: null },
  { id: 's_h', city1: 'Seattle', city2: 'Helena', length: 5, color: 'YELLOW', claimedBy: null },
  { id: 's_p1', city1: 'Seattle', city2: 'Portland', length: 1, color: 'GREY', claimedBy: null },
  { id: 's_p2', city1: 'Seattle', city2: 'Portland', length: 1, color: 'GREY', claimedBy: null },
  { id: 'p_slc', city1: 'Portland', city2: 'Salt Lake City', length: 5, color: 'BLUE', claimedBy: null },
  { id: 'p_sf1', city1: 'Portland', city2: 'San Francisco', length: 5, color: 'GREEN', claimedBy: null },
  { id: 'p_sf2', city1: 'Portland', city2: 'San Francisco', length: 5, color: 'PURPLE', claimedBy: null },
  
  // Southwest
  { id: 'sf_slc1', city1: 'San Francisco', city2: 'Salt Lake City', length: 5, color: 'ORANGE', claimedBy: null },
  { id: 'sf_slc2', city1: 'San Francisco', city2: 'Salt Lake City', length: 5, color: 'WHITE', claimedBy: null },
  { id: 'sf_la1', city1: 'San Francisco', city2: 'Los Angeles', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'sf_la2', city1: 'San Francisco', city2: 'Los Angeles', length: 3, color: 'PURPLE', claimedBy: null },
  { id: 'la_lv', city1: 'Los Angeles', city2: 'Las Vegas', length: 2, color: 'GREY', claimedBy: null },
  { id: 'la_phx', city1: 'Los Angeles', city2: 'Phoenix', length: 3, color: 'GREY', claimedBy: null },
  { id: 'la_ep', city1: 'Los Angeles', city2: 'El Paso', length: 6, color: 'BLACK', claimedBy: null },
  { id: 'lv_slc', city1: 'Las Vegas', city2: 'Salt Lake City', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'phx_sf', city1: 'Phoenix', city2: 'Santa Fe', length: 3, color: 'GREY', claimedBy: null },
  { id: 'phx_ep', city1: 'Phoenix', city2: 'El Paso', length: 3, color: 'GREY', claimedBy: null },
  { id: 'la_den', city1: 'Los Angeles', city2: 'Denver', length: 5, color: 'WHITE', claimedBy: null },
  
  // Mountain / Central
  { id: 'c_w', city1: 'Calgary', city2: 'Winnipeg', length: 6, color: 'WHITE', claimedBy: null },
  { id: 'c_h', city1: 'Calgary', city2: 'Helena', length: 4, color: 'GREY', claimedBy: null },
  { id: 'h_w', city1: 'Helena', city2: 'Winnipeg', length: 4, color: 'BLUE', claimedBy: null },
  { id: 'h_slc', city1: 'Helena', city2: 'Salt Lake City', length: 3, color: 'PURPLE', claimedBy: null },
  { id: 'h_den', city1: 'Helena', city2: 'Denver', length: 4, color: 'GREEN', claimedBy: null },
  { id: 'h_dul', city1: 'Helena', city2: 'Duluth', length: 6, color: 'ORANGE', claimedBy: null },
  { id: 'h_om', city1: 'Helena', city2: 'Omaha', length: 5, color: 'RED', claimedBy: null },
  { id: 'slc_den1', city1: 'Salt Lake City', city2: 'Denver', length: 3, color: 'RED', claimedBy: null },
  { id: 'slc_den2', city1: 'Salt Lake City', city2: 'Denver', length: 3, color: 'YELLOW', claimedBy: null },
  { id: 'den_om', city1: 'Denver', city2: 'Omaha', length: 4, color: 'PURPLE', claimedBy: null },
  { id: 'den_kc1', city1: 'Denver', city2: 'Kansas City', length: 4, color: 'BLACK', claimedBy: null },
  { id: 'den_kc2', city1: 'Denver', city2: 'Kansas City', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'den_sf', city1: 'Denver', city2: 'Santa Fe', length: 2, color: 'GREY', claimedBy: null },
  { id: 'den_okc', city1: 'Denver', city2: 'Oklahoma City', length: 4, color: 'RED', claimedBy: null },
  { id: 'sf_ep', city1: 'Santa Fe', city2: 'El Paso', length: 2, color: 'GREY', claimedBy: null },
  { id: 'sf_okc', city1: 'Santa Fe', city2: 'Oklahoma City', length: 3, color: 'BLUE', claimedBy: null },
  
  // South / Southeast
  { id: 'ep_okc', city1: 'El Paso', city2: 'Oklahoma City', length: 5, color: 'YELLOW', claimedBy: null },
  { id: 'ep_dal', city1: 'El Paso', city2: 'Dallas', length: 4, color: 'RED', claimedBy: null },
  { id: 'ep_hou', city1: 'El Paso', city2: 'Houston', length: 6, color: 'GREEN', claimedBy: null },
  { id: 'okc_kc1', city1: 'Oklahoma City', city2: 'Kansas City', length: 2, color: 'GREY', claimedBy: null },
  { id: 'okc_kc2', city1: 'Oklahoma City', city2: 'Kansas City', length: 2, color: 'GREY', claimedBy: null },
  { id: 'okc_dal1', city1: 'Oklahoma City', city2: 'Dallas', length: 1, color: 'GREY', claimedBy: null },
  { id: 'okc_dal2', city1: 'Oklahoma City', city2: 'Dallas', length: 1, color: 'GREY', claimedBy: null },
  { id: 'okc_lr', city1: 'Oklahoma City', city2: 'Little Rock', length: 2, color: 'GREY', claimedBy: null },
  { id: 'dal_lr', city1: 'Dallas', city2: 'Little Rock', length: 2, color: 'GREY', claimedBy: null },
  { id: 'dal_hou1', city1: 'Dallas', city2: 'Houston', length: 1, color: 'GREY', claimedBy: null },
  { id: 'dal_hou2', city1: 'Dallas', city2: 'Houston', length: 1, color: 'GREY', claimedBy: null },
  { id: 'dal_no', city1: 'Dallas', city2: 'New Orleans', length: 2, color: 'RED', claimedBy: null },
  { id: 'hou_no', city1: 'Houston', city2: 'New Orleans', length: 2, color: 'GREY', claimedBy: null },
  { id: 'lr_no', city1: 'Little Rock', city2: 'New Orleans', length: 3, color: 'GREEN', claimedBy: null },
  { id: 'lr_nas', city1: 'Little Rock', city2: 'Nashville', length: 3, color: 'GREY', claimedBy: null },
  
  // Midwest / Great Lakes
  { id: 'w_dul', city1: 'Winnipeg', city2: 'Duluth', length: 4, color: 'BLACK', claimedBy: null },
  { id: 'w_ssm', city1: 'Winnipeg', city2: 'Sault Ste Marie', length: 6, color: 'GREY', claimedBy: null },
  { id: 'dul_ssm', city1: 'Duluth', city2: 'Sault Ste Marie', length: 3, color: 'GREY', claimedBy: null },
  { id: 'dul_om1', city1: 'Duluth', city2: 'Omaha', length: 2, color: 'GREY', claimedBy: null },
  { id: 'dul_om2', city1: 'Duluth', city2: 'Omaha', length: 2, color: 'GREY', claimedBy: null },
  { id: 'dul_chi', city1: 'Duluth', city2: 'Chicago', length: 3, color: 'RED', claimedBy: null },
  { id: 'dul_tor', city1: 'Duluth', city2: 'Toronto', length: 6, color: 'PURPLE', claimedBy: null },
  { id: 'ssm_tor', city1: 'Sault Ste Marie', city2: 'Toronto', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ssm_m', city1: 'Sault Ste Marie', city2: 'Montreal', length: 5, color: 'BLACK', claimedBy: null },
  { id: 'om_chi', city1: 'Omaha', city2: 'Chicago', length: 4, color: 'BLUE', claimedBy: null },
  { id: 'om_kc1', city1: 'Omaha', city2: 'Kansas City', length: 1, color: 'GREY', claimedBy: null },
  { id: 'om_kc2', city1: 'Omaha', city2: 'Kansas City', length: 1, color: 'GREY', claimedBy: null },
  { id: 'kc_stl1', city1: 'Kansas City', city2: 'Saint Louis', length: 2, color: 'BLUE', claimedBy: null },
  { id: 'kc_stl2', city1: 'Kansas City', city2: 'Saint Louis', length: 2, color: 'PURPLE', claimedBy: null },
  { id: 'stl_chi1', city1: 'Saint Louis', city2: 'Chicago', length: 2, color: 'GREEN', claimedBy: null },
  { id: 'stl_chi2', city1: 'Saint Louis', city2: 'Chicago', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'stl_lr', city1: 'Saint Louis', city2: 'Little Rock', length: 2, color: 'GREY', claimedBy: null },
  { id: 'stl_nas', city1: 'Saint Louis', city2: 'Nashville', length: 2, color: 'GREY', claimedBy: null },
  
  // East / Northeast
  { id: 'tor_m', city1: 'Toronto', city2: 'Montreal', length: 3, color: 'GREY', claimedBy: null },
  { id: 'tor_pit', city1: 'Toronto', city2: 'Pittsburgh', length: 2, color: 'GREY', claimedBy: null },
  { id: 'tor_chi', city1: 'Toronto', city2: 'Chicago', length: 4, color: 'WHITE', claimedBy: null },
  { id: 'm_b1', city1: 'Montreal', city2: 'Boston', length: 2, color: 'GREY', claimedBy: null },
  { id: 'm_b2', city1: 'Montreal', city2: 'Boston', length: 2, color: 'GREY', claimedBy: null },
  { id: 'm_ny', city1: 'Montreal', city2: 'New York', length: 3, color: 'BLUE', claimedBy: null },
  { id: 'b_ny1', city1: 'Boston', city2: 'New York', length: 2, color: 'RED', claimedBy: null },
  { id: 'b_ny2', city1: 'Boston', city2: 'New York', length: 2, color: 'YELLOW', claimedBy: null },
  { id: 'ny_pit1', city1: 'New York', city2: 'Pittsburgh', length: 2, color: 'GREEN', claimedBy: null },
  { id: 'ny_pit2', city1: 'New York', city2: 'Pittsburgh', length: 2, color: 'WHITE', claimedBy: null },
  { id: 'ny_w1', city1: 'New York', city2: 'Washington', length: 2, color: 'ORANGE', claimedBy: null },
  { id: 'ny_w2', city1: 'New York', city2: 'Washington', length: 2, color: 'BLACK', claimedBy: null },
  { id: 'pit_chi1', city1: 'Pittsburgh', city2: 'Chicago', length: 3, color: 'BLACK', claimedBy: null },
  { id: 'pit_chi2', city1: 'Pittsburgh', city2: 'Chicago', length: 3, color: 'ORANGE', claimedBy: null },
  { id: 'pit_w', city1: 'Pittsburgh', city2: 'Washington', length: 2, color: 'GREY', claimedBy: null },
  { id: 'pit_rch', city1: 'Pittsburgh', city2: 'Richmond', length: 2, color: 'GREY', claimedBy: null },
  { id: 'pit_nas', city1: 'Pittsburgh', city2: 'Nashville', length: 4, color: 'YELLOW', claimedBy: null },
  
  // Southeast / Mid-Atlantic
  { id: 'w_rch1', city1: 'Washington', city2: 'Richmond', length: 1, color: 'GREY', claimedBy: null },
  { id: 'w_rch2', city1: 'Washington', city2: 'Richmond', length: 1, color: 'GREY', claimedBy: null },
  { id: 'rch_ral', city1: 'Richmond', city2: 'Raleigh', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ral_pit', city1: 'Raleigh', city2: 'Pittsburgh', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ral_atl1', city1: 'Raleigh', city2: 'Atlanta', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ral_atl2', city1: 'Raleigh', city2: 'Atlanta', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ral_ch', city1: 'Raleigh', city2: 'Charleston', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ch_atl', city1: 'Charleston', city2: 'Atlanta', length: 2, color: 'GREY', claimedBy: null },
  { id: 'ch_jax', city1: 'Charleston', city2: 'Jacksonville', length: 2, color: 'GREY', claimedBy: null },
  { id: 'jax_atl', city1: 'Jacksonville', city2: 'Atlanta', length: 2, color: 'GREY', claimedBy: null },
  { id: 'jax_m', city1: 'Jacksonville', city2: 'Miami', length: 4, color: 'PURPLE', claimedBy: null },
  { id: 'jax_no', city1: 'Jacksonville', city2: 'New Orleans', length: 5, color: 'GREY', claimedBy: null },
  { id: 'm_atl', city1: 'Miami', city2: 'Atlanta', length: 5, color: 'BLUE', claimedBy: null },
  { id: 'no_atl1', city1: 'New Orleans', city2: 'Atlanta', length: 4, color: 'YELLOW', claimedBy: null },
  { id: 'no_atl2', city1: 'New Orleans', city2: 'Atlanta', length: 4, color: 'ORANGE', claimedBy: null },
  { id: 'no_m', city1: 'New Orleans', city2: 'Miami', length: 6, color: 'RED', claimedBy: null },
  { id: 'nas_atl1', city1: 'Nashville', city2: 'Atlanta', length: 1, color: 'GREY', claimedBy: null },
  { id: 'nas_atl2', city1: 'Nashville', city2: 'Atlanta', length: 1, color: 'GREY', claimedBy: null }
];

export const USA_DESTINATION_TICKETS: DestinationTicket[] = [
  { id: 'ut1', city1: 'Boston', city2: 'Miami', points: 12 },
  { id: 'ut2', city1: 'Calgary', city2: 'Phoenix', points: 13 },
  { id: 'ut3', city1: 'Calgary', city2: 'Salt Lake City', points: 7 },
  { id: 'ut4', city1: 'Chicago', city2: 'New Orleans', points: 7 },
  { id: 'ut5', city1: 'Chicago', city2: 'Santa Fe', points: 9 },
  { id: 'ut6', city1: 'Dallas', city2: 'New York', points: 11 },
  { id: 'ut7', city1: 'Denver', city2: 'El Paso', points: 4 },
  { id: 'ut8', city1: 'Denver', city2: 'Pittsburgh', points: 11 },
  { id: 'ut9', city1: 'Duluth', city2: 'El Paso', points: 10 },
  { id: 'ut10', city1: 'Duluth', city2: 'Houston', points: 8 },
  { id: 'ut11', city1: 'Helena', city2: 'Los Angeles', points: 8 },
  { id: 'ut12', city1: 'Kansas City', city2: 'Houston', points: 5 },
  { id: 'ut13', city1: 'Los Angeles', city2: 'Chicago', points: 16 },
  { id: 'ut14', city1: 'Los Angeles', city2: 'Miami', points: 20 },
  { id: 'ut15', city1: 'Los Angeles', city2: 'New York', points: 21 },
  { id: 'ut16', city1: 'Montreal', city2: 'Atlanta', points: 9 },
  { id: 'ut17', city1: 'Montreal', city2: 'New Orleans', points: 13 },
  { id: 'ut18', city1: 'New York', city2: 'Atlanta', points: 6 },
  { id: 'ut19', city1: 'Portland', city2: 'Nashville', points: 17 },
  { id: 'ut20', city1: 'Portland', city2: 'Phoenix', points: 11 },
  { id: 'ut21', city1: 'San Francisco', city2: 'Atlanta', points: 17 },
  { id: 'ut22', city1: 'Sault Ste Marie', city2: 'Nashville', points: 8 },
  { id: 'ut23', city1: 'Sault Ste Marie', city2: 'Oklahoma City', points: 9 },
  { id: 'ut24', city1: 'Seattle', city2: 'Los Angeles', points: 9 },
  { id: 'ut25', city1: 'Seattle', city2: 'New York', points: 22 },
  { id: 'ut26', city1: 'Toronto', city2: 'Miami', points: 10 },
  { id: 'ut27', city1: 'Vancouver', city2: 'Montreal', points: 20 },
  { id: 'ut28', city1: 'Vancouver', city2: 'Santa Fe', points: 13 },
  { id: 'ut29', city1: 'Winnipeg', city2: 'Houston', points: 12 },
  { id: 'ut30', city1: 'Winnipeg', city2: 'Little Rock', points: 11 },
  { id: 'ut31', city1: 'Las Vegas', city2: 'Washington', points: 19 },
  { id: 'ut32', city1: 'Omaha', city2: 'Richmond', points: 9 },
  { id: 'ut33', city1: 'Saint Louis', city2: 'Raleigh', points: 5 },
  { id: 'ut34', city1: 'Helena', city2: 'Charleston', points: 13 },
  { id: 'ut35', city1: 'Pittsburgh', city2: 'Jacksonville', points: 6 },
  { id: 'ut36', city1: 'Oklahoma City', city2: 'Toronto', points: 10 },
  { id: 'ut37', city1: 'Salt Lake City', city2: 'Little Rock', points: 9 },
  { id: 'ut38', city1: 'Omaha', city2: 'Dallas', points: 4 },
  { id: 'ut39', city1: 'Kansas City', city2: 'Raleigh', points: 7 },
  { id: 'ut40', city1: 'Helena', city2: 'Jacksonville', points: 13 }
];
